name: abu dhabi
favicon: null
layout_spectrum: 0.1440829043276608
typography_spectrum: 0.8812894178554416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdbdb'
    - '#000000'
    - '#a8a8a8'
    - '#3f3f3f'
    - '#797979'
  brandStrength: 0.6374106365256011
  lightness: 0.6617285660468042
  saturation: 0.12948784977197647
  rhythmicContrast: 0.8161495255772024
purpose: []
